### ISSUE TITLE
[HPDCACHE VERIF ] Compile command in README doesnt exists

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/cv-hpdcache-verif#3]
Hello 

According to readme compile command should be following: This command doesnt exists. 
python3 $PROJECT_DIR/scripts/sim/sim_cmd_gen.py

It should have been
python3 $PROJECT_DIR/scripts/sim/compile.py

Thanks and Regards
Tanuj Khandelwal

**Comment by MikeOpenHWGroup** [comment]
PR #4 has been merged in.  If that resolves this Issue, please close it - thanks!
